services:
  postgres:
    container_name: postgres-javaspot
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: javaspot_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/postgres-data/javaspot